CREATE TABLE TRASH 
(
   company 		VARCHAR2(40 BYTE),
   tName 		VARCHAR2(40 BYTE) PRIMARY KEY,
   tExp 		VARCHAR2(400 BYTE),		
   tCateEGram1 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateEGram2 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateEGram3 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateEGram4 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateEGram5 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateEGram6 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateEGram7 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateNGram1 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateNGram2 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateNGram3 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateNGram4 	VARCHAR2(4 BYTE) DEFAULT '0',
   tCateNGram5 	VARCHAR2(4 BYTE) DEFAULT '0',
   REGDATE 		DATE DEFAULT SYSDATE,
   tScore		VARCHAR2(300 BYTE),
   tEco			VARCHAR2(2) DEFAULT '0'
);